Remove `deno repl` as a command affected by type checking flag
As of version `2.2.2`, the `deno repl` command is not affected by the `--check` flag. As demonstrated be

```console
➜  my_project deno repl --check
error: unexpected argument '--check' found

  tip: to pass '--check' as a value, use '-- --check'

Usage: deno repl [OPTIONS] [-- [ARGS]...]
```